---
abstract: 'test that files do not contain soft breakpoints'
author:
  - 'James FitzGibbon <jfitz@cpan.org>'
  - 'Apocalypse <APOCAL@cpan.org>'
  - 'Chisel <chisel@chizography.net>'
build_requires:
  File::Find: 0
  Test::Exception: 0
  Test::More: 0.92
  Test::Tester: 0.09
  Test::UseAllModules: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-NoBreakpoints
requires:
  Exporter: 0
  File::Find: 0
  File::Spec: 0
  Test::Builder: 0
  strict: 0
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-NoBreakpoints
  repository: git://github.com/jf647/Test-NoBreakpoints.git
version: 0.15
